name: Comment on Issues with CLI

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt update && sudo apt install gh -y

      - name: Login to GitHub CLI
        run: echo "${{secrets.GITHUB_TOKEN}}" | gh auth login --with-token

      - name: Create Issue Comment
        run: gh issue comment ${{ github.event.issue.number }} -b "Thank you for opening an issue! We will look into it as soon as possible."
